### ISSUE TITLE
Unable to compile with debian format

### ISSUE THREAD

**Issue by ryukinix** [matthewbauer/unipkg#4]
```
~/Desktop/pcsxr
❯ unipkg -P debian
makepkg: unrecognized option '-P'
```

**Comment by matthewbauer** [comment]
Sorry, I haven't been maintaining this lately. I'll gladly accept PRs but right now it is broken and I'm not using makepkg anymore.

**Comment by ryukinix** [comment]
Oh, ok!

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
